name: Build Project for PR
on:
  # Запуск только при создании или обновлении pull request в ветку main
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

        # Шаг 2: Устанавливаем JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

        # Шаг 3: Проверка докера
      - name: Sanity check Docker
        run: |
          docker --version
          docker info

        # Шаг 4: Сборка приложения
      - name: Build with Maven
        run: mvn -B clean install

      # Шаг 5: Запуск checkstyle <- новый
      - name: Run Checkstyle for payment-service-application
        working-directory: ./payment-service-app
        run: mvn -B checkstyle:check